name: Pull Request to Main
on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

jobs:
  test:
    uses: ./.github/workflows/_unit_tests.yml

  check-change-log:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Check change log
        uses: ./.github/actions/check_changelog
