name: Release tag created
on:
  push:
    tags: ["v*"]

jobs:
  version-checks:
    name: Version checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - id: validate_version_trigger
        uses: ./.github/actions/validate_version_trigger
      - uses: ./.github/actions/check_if_tag_exists
        with:
          tag: "v${{ steps.validate_version_trigger.outputs.package_version }}"
          fail_if_not_exists: "true"

  publish-to-prod:
    name: Publish "${{ github.ref_name }}" to PyPI
    needs: version-checks
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      # IMPORTANT: this permission is mandatory for Trusted Publishing
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v7

      - name: Build package with uv
        shell: bash
        run: uv build

      - name: Publish package distributions to PyPI   [---PROD---]
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://upload.pypi.org/legacy/


  bump-version:
    name: Bump version
    needs: publish-to-prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v7

      - name: Check current version
        run: |
            PACKAGE_VERSION=$( uv version --short )
            echo "CURRENT_PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV                 

      - uses: ./.github/actions/bump_version
        with:
          github_token: ${{ secrets.GIT_ADMIN_TOKEN }}
          git_ref: 'main'
          bump_type: 'patch'
          only_if_equal_to_version: ${{ env.CURRENT_PACKAGE_VERSION }}